### ISSUE TITLE
No check for NULL pointer with memchr

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#14]
https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/e976857bb471ef72519871636499d26e1498187a/sparser/sparser_dpu/dpu_host.c#L95-L96

If `'\n'` is ever missing you could end up doing arithmetic with `0`, which is probably not what you intended. I'm not sure if this is a possibility? If it is not you might want to add a comment.

**Comment by larrylikestocode** [comment]
Close for now
