### ISSUE TITLE
Use bulk transfer be used for all variables

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#16]
I noticed you're not using bulk transfer for all variables even some that are arrays. Perhaps it will not make as much as a difference for PIM-JSON since your main dataset is much larger, but I noticed an improvement when doing bulk transfer for all my variables even single integers.

https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/e976857bb471ef72519871636499d26e1498187a/sparser/sparser_dpu/dpu_host.c#L191-L204

**Comment by larrylikestocode** [comment]
Done
