### ISSUE TITLE
Comment and possibly remove shifts from find_next_set_bit

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#17]
It wasn't immediately clear to me that this was doing, since it's not checking all of the bits, just select ones. It might be worth adding a comment. 

From what I can tell you are doing the following:

```c
if (res & 65536) return 1;
if (res & 256) return 2;
if (res & 1) return 3;
return 4;
```
Depending on how often this code is called, if that's all you're doing you could remove all of the shifts and just have that saving a few cycles.

https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/e976857bb471ef72519871636499d26e1498187a/sparser/sparser_dpu/dpu/strstr_dpu_nowrite.c#L45-L53

**Comment by larrylikestocode** [comment]
Thanks for the review. Good point, going to address this

**Comment by larrylikestocode** [comment]
Done
