### ISSUE TITLE
Memory leak of query_node_t

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#19]
There's a memory leak here, memory is being allocated every time `json_node_new` is called, and two frees never occur as far as I can tell:

```c
free(n->field_name);
free(n);
```

https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/2d7b156f4877cdc75fe8c73dec6cb47af8b9ecd3/sparser/json/json_facade.h#L235-L238

**Comment by johnramsden** [comment]
Not sure if you wrote this code.

**Comment by larrylikestocode** [comment]
Sparser's code so closing the issue
