### ISSUE TITLE
Could use macro for time difference

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#21]
From PIM-common [host/include/host.h](https://github.com/UBC-ECE-Sasha/PIM-common/blob/756442d7f173256b08e54832e095626e5b9ad568/host/include/host.h#L8-L10)

ie:

```
printf("host took %g s for transferring memory\n", TIME_DIFFERENCE(start, end));
```

**Comment by larrylikestocode** [comment]
Done
