### ISSUE TITLE
Comments needed

### ISSUE THREAD

**Issue by johnramsden** [UBC-ECE-Sasha/PIM-JSON#23]
It's not immediately obvious what the following are doing, and why:

https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/2d7b156f4877cdc75fe8c73dec6cb47af8b9ecd3/sparser/sparser_dpu/dpu/strstr_dpu_nowrite.c#L88-L89

https://github.com/UBC-ECE-Sasha/PIM-JSON/blob/2d7b156f4877cdc75fe8c73dec6cb47af8b9ecd3/sparser/sparser_dpu/dpu/strstr_dpu_nowrite.c#L100-L104

Some comments explaining what `ret` and `a` represent might be worthwhile.

**Comment by larrylikestocode** [comment]
will add more comments closing now
