### ISSUE TITLE
Wrong paths for PIM-common folder

### ISSUE THREAD

**Issue by ghost** [UBC-ECE-Sasha/PIM-JSON#26]
To be able to build using the Makefile in `sparser/sparser_dpu`, paths to access files in the `PIM-common` folder are wrong.

Files concerned are:
- `sparser/dpu_common.h`
- `sparser/sparser_dpu/Makefile`

Each time there is one `../` to remove to target the `PIM-common` folder added as submodule.

**Comment by larrylikestocode** [comment]
added PIM_common as submodule
